### PR TITLE
feat: chatbot ui

### LINKED ISSUE #1: Chatbot AI
We need a nextjs 13 chatbot interface, it should just be a very simple text input at the bottom of the screen with a white background. The text responses should be centred. We will be using OpenAI's GPT-3.5-turbo.

### PR DESCRIPTION
**Pull request by Keyrxng**
Resolves #1

The ui is primitive and very simple

I used a nextjs openai starter template which I think meets the spec

### CODE REVIEW

**Comment by Keyrxng** [comment]
```====================================
spec [
  {
    role: 'system',
    content: 'This pull request context: \n' +
      `[{"login":"Keyrxng","body":"Keyrxng's pull request description:\\nResolves #1\\r\\n\\r\\nThe ui is primitive and very simple\\r\\n\\r\\nI used a nextjs openai starter template which I think meets the spec"},{"login":"assistant","body":"#1 Specification: \\nWe need a nextjs 13 chatbot interface, it should just be a very simple text input at the bottom of the screen with a white background. The text responses should be centred. We will be using OpenAI's GPT-3.5-turbo."}]`
  }
]
====================================
====================================
gptResponse {
  answer: 'Based on the PR diff, it appears that the changes made by Keyrxng meet the specification. \n' +
    '\n' +
    "Keyrxng added the necessary code to create a chat interface using Next.js and OpenAI's GPT-3.5-turbo. They added a new file `app/api/chat/route.ts` which handles the chat API endpoint and uses the OpenAI API to generate chat completions. They also added a new file `app/function-calling/page.tsx` which contains the chat interface component. \n" +
    '\n' +
    'Overall, the changes made by Keyrxng align with the specification of creating a Next.js 13 chatbot interface with a simple text input and centered text responses.',
  tokenUsage: { output: 137, input: 4432, total: 4569 }
}
====================================
INFO (http): POST / 202 - 9003ms
INFO (server): POST http://localhost:3000/ - 202
====================================
validated {
  answer: '### Have achieved specification\n' +
    'Keyrxng, you have achieved the spec and now the reviewers will let you know if there are any other changes needed.',
  tokenUsage: { output: 30, input: 447, total: 477 }
}
====================================

**Review by KxyChain — COMMENTED** [review]
Testingggg

**Pull request merged**
